# Generated by Django 5.0.6 on 2025-04-11 04:53

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('googlelogin', '0005_organizerrequest_alter_admin_table_alter_event_table_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizerNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='googlelogin.userprofile')),
            ],
            options={
                'db_table': 'organizer_notification',
            },
        ),
    ]
