# Generated by Django 5.1.5 on 2025-03-27 16:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('googlelogin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('phone_number', models.CharField(max_length=15, unique=True, validators=[django.core.validators.RegexValidator(message="Phone Number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{10,15}$')])),
                ('password', models.CharField(max_length=128)),
                ('gender', models.CharField(blank=True, max_length=10, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('image', models.TextField(blank=True, null=True)),
                ('dob', models.DateField(blank=True, null=True)),
                ('signup_date', models.DateTimeField(auto_now_add=True)),
                ('points', models.IntegerField(default=0)),
                ('verification_status', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'users"."group1',
                'ordering': ['username'],
                'managed': False,
            },
        ),
    ]
