# Generated by Django 5.1.5 on 2025-04-03 09:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('googlelogin', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=100)),
                ('profile_image', models.CharField(blank=True, max_length=255, null=True)),
                ('esewa_id', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'users"."admins',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Organizer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message="Phone Number must be entered in the format: '+999999999'.", regex='^\\+?1?\\d{10,15}$')])),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=100)),
                ('owner_names', models.TextField()),
                ('address', models.TextField(blank=True, null=True)),
                ('verification_status', models.BooleanField(default=False)),
                ('signup_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'users"."organizers',
                'managed': False,
            },
        ),
    ]
