# Generated by Django 5.1.5 on 2025-04-10 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('googlelogin', '0003_admin_organizer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('date', models.DateTimeField()),
                ('location', models.CharField(max_length=255)),
                ('capacity', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_code', models.CharField(blank=True, max_length=6, null=True, unique=True)),
                ('image', models.BinaryField(blank=True, null=True)),
            ],
            options={
                'db_table': '"users"."events"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EventHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occurrence_status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('unpaid', 'Unpaid')], default='pending', max_length=20)),
                ('marketing_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_revenue', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('verification_date', models.DateTimeField(blank=True, null=True)),
                ('failure_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'events"."event_history',
                'managed': False,
            },
        ),
    ]
