# Generated by Django 5.0.6 on 2025-04-11 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('googlelogin', '0005_organizerrequest_alter_admin_table_alter_event_table_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organizer',
            options={'managed': True},
        ),
    ]
