# Generated by Django 5.0.6 on 2025-04-13 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('googlelogin', '0008_fix_organizer_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='organizer',
            options={'managed': False},
        ),
    ]
